name: Publish Docker image

on:
  push:
    branches: ['dev-campaigns']

jobs:
  push_to_ACR:
    name: Push to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create env file
        run: |
          touch .env
          echo ${{ secrets.MONGO_URI }} >> .env
          echo ${{ secrets.HOSTNAME }} >> .env
          echo ${{ secrets.PORT }} >> .env
          echo ${{ secrets.TOKEN }} >> .env
          echo ${{ secrets.EXPIRATION }} >> .env
          cat .env

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: deepiaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD}}
      
      - run: |
          docker build . -t deepiaacr.azurecr.io/deeptarget-backend:${{ github.sha }}
          docker push deepiaacr.azurecr.io/deeptarget-backend:${{ github.sha }}
      
      # - name: Extract metadata for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: deeptarget/backend
      #     file: ./Dockerfile
